import { AssetCategoryInfo, FinancingOption, Partner } from '../types';

// Nigerian Naira formatting
export const formatNaira = (amount: number): string => {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

// App Colors
export const COLORS = {
  primary: '#22c55e',
  primaryDark: '#16a34a',
  primaryLight: '#86efac',
  secondary: '#eab308',
  accent: '#3b82f6',
  background: '#f8fafc',
  surface: '#ffffff',
  text: '#0f172a',
  textSecondary: '#64748b',
  error: '#ef4444',
  success: '#22c55e',
  warning: '#f59e0b',
  border: '#e2e8f0',
};

// Asset Categories
export const ASSET_CATEGORIES: AssetCategoryInfo[] = [
  {
    id: 'devices',
    name: 'Devices & Tools',
    icon: 'laptop',
    description: 'Laptops, phones, and work equipment',
    color: '#3b82f6',
  },
  {
    id: 'solar',
    name: 'Solar & Power',
    icon: 'sun',
    description: 'Solar panels, inverters, and power solutions',
    color: '#f59e0b',
  },
  {
    id: 'rent',
    name: 'Rent & Housing',
    icon: 'home',
    description: 'Rent financing and housing solutions',
    color: '#8b5cf6',
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'graduation-cap',
    description: 'Tuition, courses, and certifications',
    color: '#06b6d4',
  },
  {
    id: 'health',
    name: 'Health',
    icon: 'heart-pulse',
    description: 'Medical expenses and health insurance',
    color: '#ec4899',
  },
  {
    id: 'business',
    name: 'Business',
    icon: 'briefcase',
    description: 'Business equipment and working capital',
    color: '#10b981',
  },
];

// Partners (Real Nigerian fintech companies)
export const PARTNERS: Partner[] = [
  // Devices & Tools
  {
    id: 'easybuy',
    name: 'Easybuy',
    logo: 'https://easybuy.com.ng/logo.png',
    category: ['devices'],
    description: 'Get smartphones, laptops, and electronics on flexible payment plans.',
    website: 'https://easybuy.com.ng',
  },
  {
    id: 'cdcare',
    name: 'CDcare',
    logo: 'https://cdcare.ng/logo.png',
    category: ['devices'],
    description: 'Buy gadgets and appliances, pay in installments over 3-6 months.',
    website: 'https://cdcare.ng',
  },
  {
    id: 'keza',
    name: 'Keza Africa',
    logo: 'https://keza.africa/logo.png',
    category: ['devices'],
    description: 'Finance phones and laptops with flexible repayment options.',
    website: 'https://keza.africa',
  },
  // Solar & Power
  {
    id: 'mkopa',
    name: 'M-KOPA',
    logo: 'https://m-kopa.com/logo.png',
    category: ['solar', 'devices'],
    description: 'Pay-as-you-go solar and smartphone financing.',
    website: 'https://m-kopa.com',
  },
  {
    id: 'sunking',
    name: 'Sun King',
    logo: 'https://sunking.com/logo.png',
    category: ['solar'],
    description: 'Solar home systems with affordable payment plans.',
    website: 'https://sunking.com',
  },
  {
    id: 'arnergy',
    name: 'Arnergy',
    logo: 'https://arnergy.com/logo.png',
    category: ['solar'],
    description: 'Premium solar solutions for homes and businesses.',
    website: 'https://arnergy.com',
  },
  {
    id: 'auxano',
    name: 'Auxano Solar',
    logo: 'https://auxanosolar.com/logo.png',
    category: ['solar'],
    description: 'Reliable solar power systems with flexible financing.',
    website: 'https://auxanosolar.com',
  },
  // Rent & Housing
  {
    id: 'spleet',
    name: 'Spleet Africa',
    logo: 'https://spleet.africa/logo.png',
    category: ['rent'],
    description: 'Pay rent monthly instead of yearly. Find flexible housing.',
    website: 'https://spleet.africa',
  },
  {
    id: 'ule',
    name: 'Ule Homes',
    logo: 'https://ule.ng/logo.png',
    category: ['rent'],
    description: 'Rent now, pay later. Spread your rent over 12 months.',
    website: 'https://ule.ng',
  },
  {
    id: 'sofri',
    name: 'Sofri Sofri',
    logo: 'https://sofrisofri.com/logo.png',
    category: ['rent'],
    description: 'Flexible rent payment solutions for Nigerian tenants.',
    website: 'https://sofrisofri.com',
  },
  // Education
  {
    id: 'nelfund',
    name: 'NELFUND',
    logo: 'https://nelfund.gov.ng/logo.png',
    category: ['education'],
    description: 'Nigerian Education Loan Fund - Government student loans.',
    website: 'https://nelfund.gov.ng',
  },
  {
    id: 'edubanc',
    name: 'Edubanc',
    logo: 'https://edubanc.ng/logo.png',
    category: ['education'],
    description: 'School fees financing with flexible repayment.',
    website: 'https://edubanc.ng',
  },
  {
    id: 'edupoint',
    name: 'Edupoint',
    logo: 'https://edupoint.ng/logo.png',
    category: ['education'],
    description: 'Education financing for students and professionals.',
    website: 'https://edupoint.ng',
  },
  // Health
  {
    id: 'myitura',
    name: 'MyItura',
    logo: 'https://myitura.com/logo.png',
    category: ['health'],
    description: 'Healthcare financing - Pay for medical expenses in installments.',
    website: 'https://myitura.com',
  },
  // Business
  {
    id: 'sycamore',
    name: 'Sycamore',
    logo: 'https://sycamore.ng/logo.png',
    category: ['business'],
    description: 'Business loans and invoice financing for SMEs.',
    website: 'https://sycamore.ng',
  },
  {
    id: 'carbon',
    name: 'Carbon',
    logo: 'https://getcarbon.co/logo.png',
    category: ['business'],
    description: 'Quick business and personal loans in minutes.',
    website: 'https://getcarbon.co',
  },
  {
    id: 'lendha',
    name: 'Lendha',
    logo: 'https://lendha.com/logo.png',
    category: ['business'],
    description: 'Working capital and asset financing for businesses.',
    website: 'https://lendha.com',
  },
  {
    id: 'salad',
    name: 'Salad Africa',
    logo: 'https://salad.africa/logo.png',
    category: ['business'],
    description: 'Embedded credit for gig workers and freelancers.',
    website: 'https://salad.africa',
  },
];

// Sample Financing Options (Hardcoded for MVP)
export const FINANCING_OPTIONS: FinancingOption[] = [
  // Devices
  {
    id: 'macbook-air-m1',
    name: 'MacBook Air M1',
    description: 'Perfect for developers, designers, and professionals. 8GB RAM, 256GB SSD.',
    category: 'devices',
    provider: 'Keza Africa',
    totalPrice: 450000,
    monthlyPayment: 45000,
    duration: 10,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=400',
    isAffordable: true,
    features: ['0% Interest', '10 months payment', 'Free delivery', 'Warranty included'],
  },
  {
    id: 'macbook-pro-m2',
    name: 'MacBook Pro M2',
    description: 'Professional-grade laptop for heavy workloads. 16GB RAM, 512GB SSD.',
    category: 'devices',
    provider: 'CDcare',
    totalPrice: 850000,
    monthlyPayment: 95000,
    duration: 9,
    interestRate: 5,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
    isAffordable: true,
    features: ['Low interest', '9 months payment', 'Insurance included'],
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15 Pro',
    description: 'Latest iPhone with titanium design and A17 Pro chip.',
    category: 'devices',
    provider: 'Easybuy',
    totalPrice: 750000,
    monthlyPayment: 62500,
    duration: 12,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400',
    isAffordable: true,
    features: ['0% Interest', '12 months payment', 'Brand new'],
  },
  {
    id: 'dell-xps',
    name: 'Dell XPS 15',
    description: 'Premium Windows laptop for professionals. Intel i7, 16GB RAM.',
    category: 'devices',
    provider: 'CDcare',
    totalPrice: 680000,
    monthlyPayment: 68000,
    duration: 10,
    interestRate: 3,
    imageUrl: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400',
    isAffordable: true,
    features: ['3% Interest', '10 months payment', 'Genuine Windows'],
  },
  // Solar
  {
    id: 'solar-basic',
    name: '1.5kVA Solar System',
    description: 'Basic solar setup for small homes. Powers lights, fans, and phone charging.',
    category: 'solar',
    provider: 'Sun King',
    totalPrice: 200000,
    monthlyPayment: 20000,
    duration: 10,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400',
    isAffordable: true,
    features: ['0% Interest', 'Free installation', '2 year warranty'],
  },
  {
    id: 'solar-inverter',
    name: '3.5kVA Solar Inverter',
    description: 'Medium-sized solar system for homes and small offices.',
    category: 'solar',
    provider: 'Arnergy',
    totalPrice: 450000,
    monthlyPayment: 45000,
    duration: 10,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?w=400',
    isAffordable: true,
    features: ['0% Interest', 'Professional installation', 'Monitoring app'],
  },
  {
    id: 'solar-premium',
    name: '5kVA Complete Solar',
    description: 'Full home solar solution. Powers AC, fridge, and all appliances.',
    category: 'solar',
    provider: 'Auxano Solar',
    totalPrice: 1500000,
    monthlyPayment: 150000,
    duration: 10,
    interestRate: 5,
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400',
    isAffordable: false,
    features: ['Premium quality', 'Lithium batteries', '5 year warranty'],
  },
  // Rent
  {
    id: 'rent-studio',
    name: 'Studio Apartment (Lagos)',
    description: 'Self-contain in Yaba/Surulere area. Pay monthly instead of yearly.',
    category: 'rent',
    provider: 'Spleet Africa',
    totalPrice: 1200000,
    monthlyPayment: 100000,
    duration: 12,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400',
    isAffordable: true,
    features: ['Monthly payment', 'Verified properties', 'No agent fees'],
  },
  {
    id: 'rent-2bed',
    name: '2 Bedroom Flat (Lagos)',
    description: 'Nice 2 bedroom in Lekki/VI. Spread your rent over 12 months.',
    category: 'rent',
    provider: 'Ule Homes',
    totalPrice: 3600000,
    monthlyPayment: 300000,
    duration: 12,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400',
    isAffordable: false,
    features: ['Pay rent monthly', 'Premium locations', 'Flexible terms'],
  },
  // Education
  {
    id: 'edu-bootcamp',
    name: 'Tech Bootcamp',
    description: 'Full-stack development or data science bootcamp. Learn to code in 6 months.',
    category: 'education',
    provider: 'Edubanc',
    totalPrice: 500000,
    monthlyPayment: 50000,
    duration: 10,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400',
    isAffordable: true,
    features: ['0% Interest', 'Job placement support', 'Flexible schedule'],
  },
  {
    id: 'edu-masters',
    name: 'Masters Degree Financing',
    description: 'Fund your postgraduate education. Partner universities available.',
    category: 'education',
    provider: 'NELFUND',
    totalPrice: 2000000,
    monthlyPayment: 80000,
    duration: 24,
    interestRate: 5,
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400',
    isAffordable: true,
    features: ['Low interest', 'Grace period', 'Government backed'],
  },
  // Health
  {
    id: 'health-surgery',
    name: 'Medical Procedure Financing',
    description: 'Finance surgeries and major medical procedures. Partner hospitals.',
    category: 'health',
    provider: 'MyItura',
    totalPrice: 500000,
    monthlyPayment: 50000,
    duration: 10,
    interestRate: 0,
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=400',
    isAffordable: true,
    features: ['0% Interest', 'Partner hospitals', 'Quick approval'],
  },
  // Business
  {
    id: 'business-equipment',
    name: 'Business Equipment Loan',
    description: 'Finance machinery, vehicles, and equipment for your business.',
    category: 'business',
    provider: 'Lendha',
    totalPrice: 1000000,
    monthlyPayment: 100000,
    duration: 12,
    interestRate: 8,
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400',
    isAffordable: true,
    features: ['Fast approval', 'Flexible terms', 'No collateral'],
  },
  {
    id: 'business-working-capital',
    name: 'Working Capital',
    description: 'Short-term financing for inventory, payroll, and operations.',
    category: 'business',
    provider: 'Carbon',
    totalPrice: 500000,
    monthlyPayment: 90000,
    duration: 6,
    interestRate: 10,
    imageUrl: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400',
    isAffordable: true,
    features: ['Same-day disbursement', 'No paperwork', 'Repeat customers get more'],
  },
];

// Verified Corporate Domains (Sample - would be expanded in production)
export const VERIFIED_CORPORATE_DOMAINS = [
  'mtn.ng',
  'mtn.com',
  'dangote.com',
  'gtbank.com',
  'gtco.com',
  'accessbankplc.com',
  'zenithbank.com',
  'firstbanknigeria.com',
  'ubagroup.com',
  'sterlingbank.com',
  'flutterwave.com',
  'paystack.com',
  'interswitch.com',
  'andela.com',
  'microsoft.com',
  'google.com',
  'amazon.com',
  'meta.com',
  'kpmg.com',
  'pwc.com',
  'ey.com',
  'deloitte.com',
  'shell.com',
  'totalenergies.com',
  'chevron.com',
  'exxonmobil.com',
  'nlng.com',
  'cbn.gov.ng',
  'ncc.gov.ng',
  'nnpcgroup.com',
  'pau.edu.ng',
  'unilag.edu.ng',
  'ui.edu.ng',
  'oauife.edu.ng',
  'abuad.edu.ng',
  'covenantuniversity.edu.ng',
];

// Verified Freelance Platforms
export const VERIFIED_FREELANCE_PLATFORMS = [
  'linkedin.com',
  'upwork.com',
  'fiverr.com',
  'toptal.com',
  'freelancer.com',
  'guru.com',
  'behance.net',
  'dribbble.com',
  'github.com',
  'medium.com',
];

// SMS Keywords for Income Detection
export const SMS_CREDIT_KEYWORDS = [
  'credit',
  'credited',
  'received',
  'deposit',
  'payment received',
  'salary',
  'transfer from',
  'inflow',
];

export const SMS_DEBIT_KEYWORDS = [
  'debit',
  'debited',
  'withdrawal',
  'transfer to',
  'payment',
  'purchase',
  'pos',
  'atm',
];

// Demo SMS Data for Hackathon
export const DEMO_SMS_DATA = [
  {
    body: 'Credit Alert: NGN300,000.00 has been credited to your account. Ref: SALARY/JAN/2026. Bal: NGN450,000.00',
    date: new Date('2026-01-05'),
  },
  {
    body: 'Debit Alert: NGN50,000.00 was debited from your account. Ref: POS PURCHASE. Bal: NGN400,000.00',
    date: new Date('2026-01-06'),
  },
  {
    body: 'Debit Alert: NGN20,000.00 was debited from your account. Ref: UTILITY BILL. Bal: NGN380,000.00',
    date: new Date('2026-01-07'),
  },
  {
    body: 'Credit Alert: NGN50,000.00 has been credited to your account. Ref: FIVERR PAYOUT. Bal: NGN430,000.00',
    date: new Date('2026-01-08'),
  },
  {
    body: 'Debit Alert: NGN15,000.00 was debited from your account. Ref: TRANSFER TO SAVINGS. Bal: NGN415,000.00',
    date: new Date('2026-01-08'),
  },
  {
    body: 'Credit Alert: NGN300,000.00 has been credited to your account. Ref: SALARY/DEC/2025. Bal: NGN320,000.00',
    date: new Date('2025-12-05'),
  },
  {
    body: 'Credit Alert: NGN35,000.00 has been credited to your account. Ref: UPWORK PAYMENT. Bal: NGN355,000.00',
    date: new Date('2025-12-10'),
  },
];
